# This is a generated file. Not intended for manual editing.
version: "2.1"
services:
  janus-wrapper:
    build:
      context: "/home/walfhand/Documents/Perso/GameHub/src/GameHub.JanusWrapper.Api"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "gamehub/janus-wrapper:dev"
    ports:
    - "127.0.0.1:57002:57100"
    - "127.0.0.1:57202:57300"
    volumes:
    - "/home/walfhand/.nuget/packages:/home/app/.nuget/packages"
    - "/home/walfhand/Documents/Perso/GameHub/src/GameHub.JanusWrapper.Api:/app:rw"
    - "/home/walfhand/Documents/Perso/GameHub:/src:rw"
    - "/home/walfhand/.local/share/JetBrains/RiderRemoteDebugger/2023.3.3/Linux64:/opt/rider-debugger"
    - "/home/walfhand/.local/share/JetBrains/Toolbox/apps/rider/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/home/walfhand/.cache/JetBrains/Rider2023.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2024_1_29_18_58_24:/var/opt/rider-debugger:rw"
    working_dir: "/app"
